#list of fields big commerce currenlty exports
big_commerce_fields = ['Item Type',
 'Product ID',
 'Product Name',
 'Product Type',
 'Product Code/SKU',
 'Bin Picking Number',
 'Brand Name',
 'Option Set',
 'Option Set Align',
 'Product Description',
 'Price',
 'Cost Price',
 'Retail Price',
 'Sale Price',
 'Fixed Shipping Cost',
 'Free Shipping',
 'Product Warranty',
 'Product Weight',
 'Product Width',
 'Product Height',
 'Product Depth',
 'Allow Purchases?',
 'Product Visible?',
 'Product Availability',
 'Track Inventory',
 'Current Stock Level',
 'Low Stock Level',
 'Category',
 'Product Image ID - 1',
 'Product Image File - 1',
 'Product Image Description - 1',
 'Product Image Is Thumbnail - 1',
 'Product Image Sort - 1',
 'Product Image ID - 2',
 'Product Image File - 2',
 'Product Image Description - 2',
 'Product Image Is Thumbnail - 2',
 'Product Image Sort - 2',
 'Search Keywords',
 'Page Title',
 'Meta Keywords',
 'Meta Description',
 'Product Condition',
 'Show Product Condition?',
 'Sort Order',
 'Product Tax Class',
 'Product UPC/EAN',
 'Stop Processing Rules',
 'Product URL',
 'Redirect Old URL?',
 'GPS Global Trade Item Number',
 'GPS Manufacturer Part Number',
 'GPS Gender',
 'GPS Age Group',
 'GPS Color',
 'GPS Size',
 'GPS Material',
 'GPS Pattern',
 'GPS Item Group ID',
 'GPS Category',
 'GPS Enabled',
 'Tax Provider Tax Code',
 'Product Custom Fields']


pc_am_big_commerce_map =  {
    "Item Name" : "Product Name" ,
    "Item Number" : "Product Code/SKU",
    "Cost"  : "Cost Price",
    "In Stock" : "Current Stock Level",
    "Price" : "Price",
    "Department" :"Category" ,
    "Retail Price" :"Retail Price"
}

map_names = {
 "pc_to_big_commerce" : pc_am_big_commerce_map
}